name = "poseidon-db-generator"          # Cámbialo por un nombre único
compatibility_date = "2026-02-21"
main = "index.js"
compatibility_flags = ["nodejs_compat"]

# Variables de entorno (puedes ponerlas como secrets después)
[vars]
ALLOWED_HOSTS = "supabase.co,neon.tech,postgres"